language: php
php:
    - '7.1'
    - '7.2'

# services:
#     - mysql

# addons:
#     apt:
#         sources:
#             - mysql-5.7-trusty
#         packages:
#             - mysql-server

# dist: trusty

# sudo: required

before_script:
    - composer self-update
    - composer install --prefer-source --no-interaction --dev
    # - mysql -e 'create database todolist;'

script:
    - composer run test

matrix:
    allow_failures:
        - php: 7.1
        - php: 7.2

    fast_finish: true

notifications:
    on_success: never
    on_failure: always
