language: php
php:
    - '5.4'
    - '5.6'
    - '7.0'
    - hhvm

before_script:
    - composer self-update
    - composer install --prefer-source --dev

script:
    - composer run test

matrix:
    allow_failures:
        - php: 5.6
        - php: 7.0
        - php: hhvm

    fast_finish: true

notifications:
    on_success: never
    on_failure: always
